In [2]:
import numpy as np

In [4]:
lista = [1,2,3]

In [7]:
np.array(lista)

array([1, 2, 3])

In [8]:
matriz = [[1,2,3],[4,5,6]]

In [10]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
#shift + tab
# mostra detalhes da funcao 

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.zeros(4,int)

array([0, 0, 0, 0])

In [25]:
np.zeros((5,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [40]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
#matriz identidade
np.eye(4,4,0,int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [57]:
np.linspace(1,11,2)

array([ 1., 11.])

In [62]:
np.random.rand(2)

array([0.44880513, 0.98266629])

In [64]:
np.random.randn(2)

array([-2.28807189, -0.40174423])

In [67]:
# retira 3 numeros inteiros de uma distribuicao aleatoria

np.random.randint(1,11,3)

array([3, 8, 8])